# Overpermissioned ClusterRole - intentionally insecure
# Grants the vulnerable app access to secrets across the cluster
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vulnerable-app-role
  labels:
    app: vulnerable-app
    environment: demo
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps", "pods", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vulnerable-app-binding
  labels:
    app: vulnerable-app
    environment: demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vulnerable-app-role
subjects:
  - kind: ServiceAccount
    name: vulnerable-sa
    namespace: vulnerable-app
