# ============================================================================
# VULNERABLE APPLICATION SERVICE ACCOUNT - INSECURE CONFIGURATION
# ============================================================================
#
# PURPOSE:
# Creates a ServiceAccount for the vulnerable application. While this file
# looks innocuous, the associated RBAC configuration (rbac.yaml) grants
# excessive permissions that violate the principle of least privilege.
#
# ============================================================================
# SECURITY ISSUES
# ============================================================================
#
# This ServiceAccount has several security problems:
#
# 1. OVERPERMISSIONED RBAC (see rbac.yaml):
#    This ServiceAccount is bound to a ClusterRole that grants:
#    - Read access to secrets across ALL namespaces
#    - Ability to exec into pods across ALL namespaces
#    - Read access to deployments and services cluster-wide
#
# 2. TOKEN AUTO-MOUNTING NOT DISABLED:
#    Without explicitly setting automountServiceAccountToken: false,
#    the ServiceAccount token is automatically mounted into pods.
#
#    Attack scenario:
#    - Attacker compromises the container
#    - Reads token from /var/run/secrets/kubernetes.io/serviceaccount/token
#    - Uses token to authenticate to Kubernetes API
#    - Exploits the overpermissioned ClusterRole to:
#      * Read secrets (credentials, API keys) from all namespaces
#      * Exec into other pods to pivot laterally
#      * Enumerate the entire cluster
#
# ============================================================================
# COMPARISON WITH COMPLIANT SERVICE ACCOUNT
# ============================================================================
#
# Vulnerable ServiceAccount (this file):
#   - Token auto-mounted (default behavior)
#   - Bound to ClusterRole (cluster-wide permissions)
#   - Can access secrets across namespaces
#   - Can exec into pods
#
# Compliant ServiceAccount (compliant-app/serviceaccount.yaml):
#   - automountServiceAccountToken: false
#   - No RBAC bindings (no additional permissions)
#   - Cannot access Kubernetes API meaningfully
#   - Follows principle of least privilege
#
# ============================================================================
# SERVICE ACCOUNT TOKEN DETAILS
# ============================================================================
#
# When automountServiceAccountToken is NOT explicitly false:
#
# 1. Token is mounted at:
#    /var/run/secrets/kubernetes.io/serviceaccount/token
#
# 2. The token can be used with curl:
#    TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
#    curl -H "Authorization: Bearer $TOKEN" \
#         --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
#         https://kubernetes.default.svc/api/v1/namespaces/default/secrets
#
# 3. With the overpermissioned ClusterRole, this allows:
#    - kubectl get secrets --all-namespaces
#    - kubectl exec -it <any-pod> -- /bin/sh
#    - kubectl get pods,deployments,services --all-namespaces
#
# ============================================================================
# KYVERNO POLICIES THAT CAN ENFORCE THIS
# ============================================================================
#
# 1. Require automountServiceAccountToken: false
#    ClusterPolicy that validates pods/deployments disable token mounting
#
# 2. Block ClusterRoleBindings for application workloads
#    ClusterPolicy that prevents binding ClusterRoles to app ServiceAccounts
#
# 3. Block sensitive RBAC permissions
#    ClusterPolicy that denies rules granting access to secrets or pods/exec
#
# Example Kyverno policy:
#
#   apiVersion: kyverno.io/v1
#   kind: ClusterPolicy
#   metadata:
#     name: require-sa-token-disabled
#   spec:
#     validationFailureAction: enforce
#     rules:
#       - name: check-automount
#         match:
#           resources:
#             kinds:
#               - Pod
#         validate:
#           message: "Service account tokens must not be auto-mounted"
#           pattern:
#             spec:
#               automountServiceAccountToken: false
#
# ============================================================================
# REGULATORY REQUIREMENTS
# ============================================================================
#
# - PCI-DSS 7.1: Limit access to system components to only those individuals
#   whose job requires such access
#
# - PCI-DSS 7.2.1: Coverage of all system components
#   (ServiceAccounts are system components)
#
# - HIPAA 164.312(a)(1): Implement technical policies for access control
#
# - NIST 800-53 AC-2: Account Management
#   (ServiceAccounts need same rigor as user accounts)
#
# - NIST 800-53 AC-6: Least Privilege
#   (ServiceAccounts should have minimal necessary permissions)
#
# ============================================================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: vulnerable-sa
  namespace: vulnerable-app
  labels:
    app: vulnerable-app
    environment: demo
# ============================================================================
# MISSING: automountServiceAccountToken: false
# ============================================================================
# This ServiceAccount allows automatic token mounting.
# Compare with compliant-app/serviceaccount.yaml which includes:
#
#   automountServiceAccountToken: false
#
# This single line prevents the token from being accessible inside containers,
# significantly reducing the blast radius if the container is compromised.
# ============================================================================
