apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
  annotations:
    policies.kyverno.io/title: Disallow Latest Tag
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      The ':latest' tag is mutable and can cause unexpected behavior when
      images are updated. This policy blocks images using the ':latest'
      tag or no tag at all, ensuring deployment reproducibility required
      by change management controls.
    compliance.regulated/ncua: "NCUA Supervisory Priority - Change Management"
    compliance.regulated/osfi-b13: "OSFI B-13 Section 5.2 - Configuration Management"
    compliance.regulated/dora: "DORA Article 9(4)(e) - Change Management"
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: validate-image-tag-containers
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: >-
          Using the ':latest' image tag or no tag is not allowed.
          Regulatory requirement: Change management controls require
          explicit, immutable image versions. Specify an explicit
          image tag (e.g., nginx:1.25.4).
        pattern:
          spec:
            containers:
              - image: "*:*"
        deny:
          conditions:
            any:
              - key: "{{ request.object.spec.containers[].image }}"
                operator: AnyIn
                value:
                  - "*:latest"
    - name: validate-image-tag-init-containers
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          - key: "{{ request.object.spec.initContainers[] || `[]` | length(@) }}"
            operator: GreaterThanOrEquals
            value: 1
      validate:
        message: >-
          Init containers must not use the ':latest' tag.
          Specify an explicit image tag.
        pattern:
          spec:
            initContainers:
              - image: "*:*"
