apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resource-limits
  annotations:
    policies.kyverno.io/title: Require Resource Limits
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Resource limits prevent containers from consuming excessive cluster
      resources, which is critical for operational resilience in financial
      services. This policy requires all containers to specify CPU and
      memory limits.
    compliance.regulated/ncua: "NCUA Supervisory Priority - Operational Resilience"
    compliance.regulated/osfi-b13: "OSFI B-13 Section 6.1 - Capacity Management"
    compliance.regulated/dora: "DORA Article 11 - ICT Capacity and Performance"
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-limits-containers
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: >-
          CPU and memory limits are required for all containers.
          Regulatory requirement: Operational resilience requires
          resource boundaries. Add resources.limits.cpu and
          resources.limits.memory to container spec.
        pattern:
          spec:
            containers:
              - resources:
                  limits:
                    memory: "?*"
                    cpu: "?*"
    - name: require-limits-init-containers
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          - key: "{{ request.object.spec.initContainers[] || `[]` | length(@) }}"
            operator: GreaterThanOrEquals
            value: 1
      validate:
        message: >-
          CPU and memory limits are required for init containers.
        pattern:
          spec:
            initContainers:
              - resources:
                  limits:
                    memory: "?*"
                    cpu: "?*"
