apiVersion: aquasecurity.github.io/v1alpha1
kind: ConfigAuditReport
metadata:
  name: vulnerability-scan-policy
  namespace: trivy-system
  labels:
    app: trivy-operator
    environment: demo
spec:
  # Scan policy configuration for regulated environments
  # This serves as a reference for configuring vulnerability thresholds

  # Critical vulnerabilities must be remediated within 24 hours
  # High vulnerabilities must be remediated within 7 days
  # Medium vulnerabilities must be remediated within 30 days
  # Low vulnerabilities should be tracked and reviewed quarterly

  scanner:
    name: Trivy
    vendor: Aqua Security
    version: "0.58"

---
# Example: Custom scan policy for financial services
# Apply this ConfigMap to configure Trivy scanning behavior
apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-operator-scan-policy
  namespace: trivy-system
  labels:
    app: trivy-operator
data:
  # Block deployments with CRITICAL vulnerabilities
  policy.critical.block: "true"
  # Alert on HIGH vulnerabilities
  policy.high.alert: "true"
  # SLA timelines (for documentation and alerting)
  policy.critical.sla_hours: "24"
  policy.high.sla_days: "7"
  policy.medium.sla_days: "30"
  policy.low.sla_days: "90"
