# ============================================================================
# COMPLIANT APPLICATION SERVICE ACCOUNT - MINIMAL PERMISSIONS
# ============================================================================
#
# PURPOSE:
# Creates a ServiceAccount with the principle of least privilege.
# This ServiceAccount has NO additional RBAC permissions and explicitly
# disables automatic token mounting.
#
# ============================================================================
# SECURITY CONTROLS IMPLEMENTED
# ============================================================================
#
# 1. automountServiceAccountToken: false
#    - Prevents token from being mounted in containers
#    - Container cannot authenticate to Kubernetes API
#    - Eliminates credential theft risk if container is compromised
#
# 2. No RBAC bindings
#    - No Role or ClusterRole bound to this ServiceAccount
#    - ServiceAccount has only default, minimal permissions
#    - Cannot read, write, or modify any Kubernetes resources
#
# ============================================================================
# COMPARISON WITH VULNERABLE APP SERVICE ACCOUNT
# ============================================================================
#
# | Aspect                        | Vulnerable SA       | Compliant SA        |
# |-------------------------------|---------------------|---------------------|
# | Token Auto-Mounting           | Enabled (default)   | Disabled            |
# | RBAC Bindings                 | ClusterRole (wide)  | None                |
# | Secret Access                 | All namespaces      | None                |
# | Pod Exec Access               | All namespaces      | None                |
# | Blast Radius if Compromised   | Entire cluster      | Container only      |
#
# ============================================================================
# WHY DISABLE TOKEN MOUNTING?
# ============================================================================
#
# When automountServiceAccountToken is true (default):
#
# 1. Token is mounted at:
#    /var/run/secrets/kubernetes.io/serviceaccount/token
#
# 2. Attacker in compromised container can:
#    TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
#    curl -H "Authorization: Bearer $TOKEN" \
#         https://kubernetes.default.svc/api/v1/...
#
# 3. Even with minimal permissions, token allows:
#    - Discovery of Kubernetes API version
#    - Potential privilege escalation via RBAC misconfigurations
#    - Reconnaissance of cluster structure
#
# When automountServiceAccountToken is false:
#
# 1. No token file exists in the container
# 2. Container cannot authenticate to Kubernetes API
# 3. Attack surface is limited to the application itself
#
# ============================================================================
# WHEN WOULD YOU NEED API ACCESS?
# ============================================================================
#
# Most applications do NOT need Kubernetes API access. Cases where you might:
#
# 1. Kubernetes Operators/Controllers:
#    - Manage custom resources
#    - Need specific RBAC for those resources only
#
# 2. Service Discovery:
#    - Reading service endpoints
#    - Better solved with DNS (service.namespace.svc.cluster.local)
#
# 3. Dynamic Configuration:
#    - Reading ConfigMaps/Secrets
#    - Better solved with volume mounts or external secret managers
#
# 4. Cluster Monitoring:
#    - Prometheus service discovery
#    - Should use dedicated monitoring ServiceAccounts
#
# IF API ACCESS IS REQUIRED:
#   1. Keep automountServiceAccountToken: false in the ServiceAccount
#   2. Set automountServiceAccountToken: true ONLY in the specific pod
#   3. Create a Role (not ClusterRole) with minimal permissions
#   4. Use RoleBinding (not ClusterRoleBinding) to limit scope
#
# ============================================================================
# KYVERNO POLICIES FOR SERVICE ACCOUNTS
# ============================================================================
#
# 1. Require Token Mounting Disabled:
#
#    apiVersion: kyverno.io/v1
#    kind: ClusterPolicy
#    metadata:
#      name: require-sa-token-disabled
#    spec:
#      validationFailureAction: enforce
#      rules:
#        - name: check-automount-pod
#          match:
#            resources:
#              kinds:
#                - Pod
#          validate:
#            message: "Pods must disable SA token automounting"
#            pattern:
#              spec:
#                automountServiceAccountToken: false
#
# 2. Block Default ServiceAccount:
#
#    apiVersion: kyverno.io/v1
#    kind: ClusterPolicy
#    metadata:
#      name: block-default-sa
#    spec:
#      validationFailureAction: enforce
#      rules:
#        - name: require-specific-sa
#          match:
#            resources:
#              kinds:
#                - Pod
#          validate:
#            message: "Pods must use a specific ServiceAccount, not 'default'"
#            pattern:
#              spec:
#                serviceAccountName: "!default"
#
# ============================================================================
# REGULATORY REQUIREMENTS
# ============================================================================
#
# PCI-DSS:
#   - 7.1: Limit access to system components (no RBAC bindings)
#   - 7.2.1: Coverage of all system components (ServiceAccount governance)
#   - 7.2.2: Restrict based on job function (app doesn't need API access)
#
# HIPAA:
#   - 164.312(a)(1): Access control mechanisms (token disabled)
#   - 164.312(d): Authentication (no credentials available to steal)
#
# SOC 2:
#   - CC6.1: Logical access controls (minimal permissions)
#   - CC6.2: User access authorization (no unnecessary access)
#   - CC6.3: Role-based access (no RBAC = no role-based access needed)
#
# NIST 800-53:
#   - AC-2: Account management (dedicated SA, documented purpose)
#   - AC-6: Least privilege (no permissions beyond default)
#   - AC-6(1): Authorize specific functions only (none authorized)
#   - IA-2: Identification and authentication (token disabled)
#
# ============================================================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: compliant-sa
  namespace: compliant-app
  labels:
    app: compliant-app
    environment: demo
# =============================================================================
# SECURITY CONTROL: Disable Token Auto-Mounting
# =============================================================================
# This is the most important security setting for ServiceAccounts.
#
# WHY THIS IS SET AT SERVICEACCOUNT LEVEL:
# - Applies to all pods using this ServiceAccount
# - Can't be accidentally overridden by pod authors
# - Central point of control
#
# DEFENSE IN DEPTH:
# The Deployment also sets automountServiceAccountToken: false at pod level.
# Both settings should be used for redundancy.
#
# REGULATORY ALIGNMENT:
# - NIST 800-53 AC-6: Principle of least privilege
# - PCI-DSS 7.1: Limit access to only what's needed
# - CIS Benchmark: Minimize ServiceAccount token usage
# =============================================================================
automountServiceAccountToken: false

# =============================================================================
# NOTE: NO RBAC BINDINGS
# =============================================================================
# Unlike the vulnerable-app, this ServiceAccount has NO Role or ClusterRole
# bindings. The most secure RBAC configuration is often NO additional
# permissions at all.
#
# The compliant app:
#   - Doesn't need to talk to Kubernetes API
#   - Doesn't need to read secrets or configmaps via API
#   - Uses volume mounts for configuration (not API calls)
#   - Uses DNS for service discovery (not API calls)
#
# If your application truly needs Kubernetes API access:
#
#   apiVersion: rbac.authorization.k8s.io/v1
#   kind: Role
#   metadata:
#     name: compliant-app-role
#     namespace: compliant-app  # Namespace-scoped, not cluster-wide
#   rules:
#     - apiGroups: [""]
#       resources: ["configmaps"]  # Only specific resources
#       resourceNames: ["app-config"]  # Only specific names
#       verbs: ["get"]  # Only specific verbs
#
#   ---
#   apiVersion: rbac.authorization.k8s.io/v1
#   kind: RoleBinding  # Not ClusterRoleBinding
#   metadata:
#     name: compliant-app-binding
#     namespace: compliant-app
#   roleRef:
#     apiGroup: rbac.authorization.k8s.io
#     kind: Role
#     name: compliant-app-role
#   subjects:
#     - kind: ServiceAccount
#       name: compliant-sa
#       namespace: compliant-app
#
# =============================================================================
