apiVersion: v1
kind: ServiceAccount
metadata:
  name: compliant-sa
  namespace: compliant-app
  labels:
    app: compliant-app
    environment: demo
# Minimal service account - no additional permissions needed
automountServiceAccountToken: false
